### PR TITLE
add basic ci

### PR DESCRIPTION
**Pull request by prolificcoder**
Add basic flutter CI into the repo. 

This job checks out the code, builds, runs unit tests

### CODE REVIEW

**Comment by GhostWalker562** [comment]
Looks good to me! 👍

**Comment by GhostWalker562** [comment]
Looks good to me. For future PRs, adding a description is should be necessary.
@Josiassejod1

**Comment by prolificcoder** [comment]
> Looks good to me. For future PRs, adding a description should be necessary. @Josiassejod1

 I am working with @devbrandonlong and thought I can add some basic CI

Thanks for the review. I am figuring out how to test this, jobs are not getting picked up 
see: https://stackoverflow.com/a/61992817/31252
 
 But I think it _should_ be good to merge

**Comment by devbrandonlong** [comment]
@prolificcoder I went ahead and merged that into my branch here: https://github.com/devbrandonlong/flutterbook/pull/1

**Pull request merged**
