### PR TITLE
Flutterbook Improvements

### PR DESCRIPTION
**Pull request by Josiassejod1**
This pr is pretty hefty but this is the gist of the new features that are introduced (these have been reviewed individually, this is just the culmination together) 
 

- [Documentation Page](https://github.com/GetDutchie/flutterbook/pull/8) (Users are able to create documentation passing in a Future<String>)
- Considerations, this way allows docs to be passed in either using a string or being loaded from the assets folder
- Since ```dart:io```  has limitations for web, the only way to read on the file system is through the bundled assets
- This was the best solution, we tried referencing the path, but only absolute paths worked when trying to use the flutterbook package in other projects

https://user-images.githubusercontent.com/12024422/145451474-45dbd7c7-a398-45e8-b39f-cd51f91348a4.mov

- [Add Pan and Zoom](https://github.com/GetDutchie/flutterbook/pull/5)
- [Device Preview](https://github.com/GetDutchie/flutterbook/pull/4)

### CODE REVIEW

**Comment by Josiassejod1** [comment]
@GhostWalker562 @aarontwf  let me know what you think

**Comment by GhostWalker562** [comment]
I'll take a look at this this weekend. Thank you so much!

**Comment by Josiassejod1** [comment]
no doubt going to add copy and past functionality as well

**Comment by GhostWalker562** [comment]
I wasn't able to look over it completely this weekend. I have finals this week so it won't be until next weekend will I be able to go over the rest. I'm also launching a crypto protocol soon so thing have to wait a bit. I'll be back :)

**Comment by Josiassejod1** [comment]
Got it no problem keep me up to date

**Comment by Josiassejod1** [comment]
bumping this @GhostWalker562

**Comment by GhostWalker562** [comment]
Still have been busy, I apologize for the delay.

**Comment by GhostWalker562** [comment]
@Josiassejod1 I might allow you to become a contributor solely because I don't have a lot of time as of right now. Been really invested into a blockchain protocol so I can't find to work on this. If you would like the role, please email me at moonsdontburn@outlook.com

**Comment by Josiassejod1** [comment]
> @Josiassejod1 I might allow you to become a contributor solely because I don't have a lot of time as of right now. Been really invested into a blockchain protocol so I can't find to work on this. If you would like the role, please email me at [moonsdontburn@outlook.com](mailto:moonsdontburn@outlook.com)

No problem just emailed you.

**Comment by Josiassejod1** [comment]
@GhostWalker562 you checked it out?

**Pull request merged**
